### ISSUE TITLE
install error when running ./bootstrap.py on mac

### ISSUE THREAD

**Issue by wanghan02** [martine/ninja#986]
Errors occurred when I run bootstrap.py. ninja is not generated. 

macbuild:ninja *$ ./bootstrap.py 
DEPRECATED: this script will be deleted.
use "configure.py --bootstrap" instead.
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
Undefined symbols for architecture x86_64:
  "std::__throw_out_of_range_fmt(char const*, ...)", referenced from:
      ElideMiddle(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) in libninja.a(util.o)
      ParseVersion(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, int*) in libninja.a(version.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
when running:  g++ -Lbuild -o ninja build/ninja.o -lninja
Traceback (most recent call last):
  File "configure.py", line 494, in <module>
    variables=[('libs', libs)])
  File "configure.py", line 148, in build
    self._run_command(self._expand(cmd, local_vars))
  File "configure.py", line 169, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'g++ -Lbuild -o ninja build/ninja.o -lninja' returned non-zero exit status 1
Traceback (most recent call last):
  File "./bootstrap.py", line 23, in <module>
    subprocess.check_call([sys.executable, 'configure.py', '--bootstrap'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'configure.py', '--bootstrap']' returned non-zero exit status 1

**Comment by wanghan02** [comment]
Issue solved. I installed gcc and it set CXX to g++. Changed it back to clang and it works fine.
